apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
  - image: registry.internal.iosis.tech/swiftness-web
    context: .
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - ./k8s/swiftness-web-deployment.yaml
  - ./k8s/certificates.yaml
  - ./k8s/issuer.yaml
